#!/bin/bash

# For some UNKOWN reason "build" script is not invoked!!!
# For some unknown reason below env variable is not visible to Maven build!!!
#MAVEN_ARGS="clean package -Popenshift -DskipTests -pl \"!profiles/killpay\""
MAVEN_ARGS="clean package -Popenshift -DskipTests -pl \"account,api,beatrix,catalog,subscription,entitlement,invoice,junction,overdue,payment,usage,util,jaxrs,tenant,currency,profiles/killbill\""
export MAVEN_ARGS


echo ""
echo "MAVEN_ARGS: $MAVEN_ARGS"
echo ""
echo "==================="
echo "Trifon - BUILD - OK"
echo "==================="
echo ""